### ISSUE TITLE
ImportError: No module named errors

### ISSUE THREAD

**Issue by gduffley** [suever/dicomSort#26]
Hey, hope it's okay that I leave a bug report as an issue. Your errors class seems have disappeared from the mater branch. Is the import no longer needed?

**Comment by suever** [comment]
Not a problem at all! Are you referring to [this line](https://github.com/suever/dicomSort/blob/9ef2986596667e69764408b7bf63f4f30e9a7e2e/dicomsorter.py#L11)? If so, the reason for that error is that I have changed the version of pydicom that is used by this project. You'll want to upgrade your local install of pydicom to 0.9.9 which will have the `dicom.errors` module

**Comment by gduffley** [comment]
That was the problem. Thanks! Only thing is that I still get the "Update Available" notification even though the CLI says I'm running 2.1.8

**Comment by suever** [comment]
Can you open the Debug window (ctrl + D) and type in `gui.__version__` and paste the result here? Also what do you get when you go to https://www.dicomsort.com/current ?

**Comment by suever** [comment]
And just to check, you are at the tip of `master`, right?

**Comment by gduffley** [comment]
I get 2.1.8 when I go to the URL, but I get 2.1.7 when I type in gui.__version__. Let me just rebase with the tip of master to make sure

**Comment by gduffley** [comment]
I just needed to reset my repo. Something happened when I went back to an old commit before you informed me that I needed to update pydicom. Sorry for the bad bug reports and thank you for maintaining this repo. I came across it after writing my own pydicom based CLI sorted, and yours is  100x better.

**Comment by suever** [comment]
For future reference, the version number is defined [here](https://github.com/suever/dicomSort/blob/master/gui/__init__.py#L24)

**Comment by suever** [comment]
Glad that it's working well for you. It is in need of a little bit of TLC. If you have specific issues or suggestions feel free to let me know.
