### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by gdevenyi** [suever/dicomsort#39]
Current code has python2isms like bare "print" statements.

**Comment by suever** [comment]
Thanks for reporting this @gdevenyi. I'll take a look and try to version bump some of the dependencies while I'm at it. I'll link any updates to this issue. What particular version of Python 3 are you using?

**Comment by gdevenyi** [comment]
I was using 3.7.1, but in general, you can with little tweaking get hybrid py2/py3 support if you use/follow https://python-future.org/

**Comment by suever** [comment]
Just noting that I will be working on this this week as part of the 3.0 release (added this issue to the milestone)

**Comment by suever** [comment]
Tracking this in https://github.com/suever/dicomsort/pull/59

Still working through a few issues but getting very close to an RC

**Comment by suever** [comment]
Going to go ahead and resolve this since tests are all currently passing. If there are issues with the release candidate, we can file those as separate issues!
