### ISSUE TITLE
Need to port to python3

### ISSUE THREAD

**Issue by trwood84** [suever/dicomsort#41]
It would be great to port this useful code to python3. I may do it myself and add a branch. If anyone else has already done this, please let me know!

**Comment by suever** [comment]
@trwood84 This is on the list of things to do to bring this into the last decade 😄 

I need to revisit to see what is required to support Python 3. The nuts and bolts of the upgrade are pretty straight-forward, but the last I looked I think the tie-ups were pydicom (which now fully supports python 3.x), wxpython (which should support it in 4.x), and then `cx_freeze` which is used to bundle the application.

Happy to use this thread as a discussion of the work that needs to be done to get Python 3.x support and then we can knock that out and any way that you can help would be great!

Out of curiosity, which platform are you running this on?

**Comment by trwood84** [comment]
Happy to help if I can! I am on Windows at work, which is where I would like to use this.  I have python3.7.3, cx_freeze-6.0, wxpython 4.0.6.    pydicom seems to be playing OK with python 3 for me currently, which is good!   From the first glance at errors, it looks a few simple things like print statements, which is easy to change and the use of python error tracking. I have not written in error tracking before, so it is not clear to me how to fix that yet.

**Comment by trwood84** [comment]
OK, I tried clearing out the more obvious errors and mostly ripped out the error reporting for now.  Now replacing the use of 'iteritems' with 'items'  in __init__.py.  (Now items does everything iteritems used to do and so 'iteritems' was removed, apparently). https://stackoverflow.com/questions/13998492/when-should-iteritems-be-used-instead-of-items .  Making progress!

**Comment by suever** [comment]
If it's any help, I had a branch `js_wxpython_4.0.4` where I was working on wxpython 4.x changes

**Comment by trwood84** [comment]
Ok, thanks! Where can I find that?

**Comment by suever** [comment]
@trwood84 https://github.com/suever/dicomSort/tree/js_wxpython_4.0.4 and the diff: https://github.com/suever/dicomSort/compare/js_wxpython_4.0.4

**Comment by lmlacerda** [comment]
Dear @suever, just a quick follow-up: I looked at the changes you suggest [here](https://github.com/suever/dicomSort/issues/41#issuecomment-531368686) and it worked! Back on track now. 

Thank you again for the software

**Comment by suever** [comment]
Closing this in favor of https://github.com/suever/dicomsort/issues/39
